name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# 设置权限以增强安全性
permissions:
  contents: read
  security-events: write
  actions: read

jobs:
  build-test:
    runs-on: ubuntu-latest
    timeout-minutes: 30 # 设置超时防止无限运行

    strategy:
      matrix:
        node-version: [18.x, 19.x, 20.x, 21.x, 22.x, 23.x, 24.x] # 测试不同 Node 版本
      fail-fast: false # 不因一个版本失败而停止其他版本的测试

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        # 获取完整历史以支持某些工具
        fetch-depth: 0

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm' # 缓存依赖
        registry-url: 'https://registry.npmjs.org'

    - name: Cache node modules
      uses: actions/cache@v4
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Install dependencies
      run: npm ci # 使用 ci 更快更可靠

    - name: Audit dependencies
      run: npm audit --audit-level=high
      continue-on-error: true # 不因审计失败而停止构建

    - name: Snyk Security Scan
      uses: snyk/actions@0.4.0
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        args: --severity-threshold=high --file=package.json
      continue-on-error: true # 不因安全扫描失败而停止构建

    - name: Upload Snyk results to GitHub Code Scanning
      uses: github/codeql-action/upload-sarif@v3
      if: always()
      with:
        sarif_file: snyk.sarif
      continue-on-error: true

    - name: Lint code
      run: npm run lint --if-present # 如果定义了 lint 脚本则运行

    - name: Run tests with coverage
      run: npm test -- --coverage --coverageReporters=text-lcov --coverageReporters=json
      env:
        NODE_OPTIONS: --experimental-vm-modules

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4
      if: matrix.node-version == '20.x' # 只在一个版本上传覆盖率
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./coverage/lcov.info
        flags: unittests
        name: codecov-umbrella
      continue-on-error: true

    - name: Build project
      run: npm run build

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      if: matrix.node-version == '20.x' # 只在一个版本上传构建产物
      with:
        name: build-artifacts
        path: dist/
        retention-days: 7